#### -----------------------------------------------------------------------------------------------------------------------------------
### NAMA    : Natalie Fuad
### NIM     : 2109106040

####
### POSTTEST 7 - TENSORFLOW
#### -----------------------------------------------------------------------------------------------------------------------------------

## Import library tensorflow

In [5]:
import tensorflow as tf

# Lakukan beberapa point berikut:
## --------------------------------------------------------------------------------------------------------------------
#### - Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor
#### - Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor
#### - Tampilkan dimensi dari kedua variable tersebut
#### - Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)
#### - Tampilkan nilai maksimal dan minimal dari variable random_tensor
#### - Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)
#### - Tampilkan hasil sorting dari kedua variable di atas. (descending)
## --------------------------------------------------------------------------------------------------------------------

### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor
### --------------------------------------------------------------------------------------------------------------------

In [67]:
random_tensor = tf.random.normal([5,5], seed = 1)

print("\n----------    ++    -------------    ++    ----------")
print("\n          Tensor Dari Variable random Tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print(random_tensor, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

          Tensor Dari Variable random Tensor

----------    ++    -------------    ++    ----------

tf.Tensor(
[[-0.3744468   0.61860144 -0.6192134   0.9124507   0.6950061 ]
 [-0.17951003 -0.37561563 -0.1350087   0.6676718   0.4242158 ]
 [-0.31347093 -0.27241856  1.1854254   0.34320396  1.4505777 ]
 [-0.29796734 -1.4172324   0.6069386  -1.4060947  -0.8780423 ]
 [-0.4037651   0.37089893 -1.0725715  -0.7477049  -1.1893758 ]], shape=(5, 5), dtype=float32) 

----------    ++    -------------    ++    ----------



### --------------------------------------------------------------------------------------------------------------------
### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor
### --------------------------------------------------------------------------------------------------------------------

In [66]:
listTensor = [2, 3, 5, 7, 11]
listTensor1 = [13, 17, 19, 23, 29]
listTensor2 = [31, 37, 41, 43, 47]
listTensor3 = [53, 59, 61, 67, 71]
listTensor4 = [73, 79, 83, 89, 97]
prime_tensor = tf.convert_to_tensor([listTensor, listTensor1, listTensor2, listTensor3, listTensor4], dtype = tf.float32)

print("\n----------    ++    -------------    ++    ----------")
print("\n          Tensor Dari Variable Prime Tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print(prime_tensor, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

          Tensor Dari Variable Prime Tensor

----------    ++    -------------    ++    ----------

tf.Tensor(
[[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32) 

----------    ++    -------------    ++    ----------



### --------------------------------------------------------------------------------------------------------------------
### Tampilkan dimensi dari kedua variable tersebut
### --------------------------------------------------------------------------------------------------------------------

In [61]:
print("\n----------    ++    -------------    ++    ----------")
print("\n         Dimensi dari variable random tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print("                      ", random_tensor.shape, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

         Dimensi dari variable random tensor

----------    ++    -------------    ++    ----------

                       (5, 5) 

----------    ++    -------------    ++    ----------



In [63]:
print("\n----------    ++    -------------    ++    ----------")
print("\n         Dimensi dari variable prime tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print("                      ", prime_tensor.shape, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

         Dimensi dari variable prime tensor

----------    ++    -------------    ++    ----------

                       (5, 5) 

----------    ++    -------------    ++    ----------



### --------------------------------------------------------------------------------------------------------------------
### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)
### --------------------------------------------------------------------------------------------------------------------
#### (Pertambahan, Perkalian, Pembagian, Logaritma, dan Pangkat)

## Pertambahan

In [70]:
pertambahan = tf.add(random_tensor, prime_tensor)

print("\n------------------    ++    -------------    ++    ------------------")
print("\n      Hasil Pertambahan Variabel Random tensor dan prime tensor\n")
print("------------------    ++    -------------    ++    ------------------\n")
print("                      ", pertambahan, "\n\n------------------    ++    -------------    ++    ------------------\n")


------------------    ++    -------------    ++    ------------------

      Hasil Pertambahan Variabel Random tensor dan prime tensor

------------------    ++    -------------    ++    ------------------

                       tf.Tensor(
[[ 1.6255531  3.6186013  4.3807864  7.912451  11.695006 ]
 [12.82049   16.624384  18.864992  23.667671  29.424215 ]
 [30.68653   36.72758   42.185425  43.343204  48.450577 ]
 [52.702034  57.582767  61.606937  65.5939    70.121956 ]
 [72.59624   79.370895  81.92743   88.2523    95.81062  ]], shape=(5, 5), dtype=float32) 

------------------    ++    -------------    ++    ------------------



## Perkalian

In [71]:
perkalian = tf.multiply(random_tensor, prime_tensor)

print("\n------------------    ++    -------------    ++    ------------------")
print("\n      Hasil Perkalian Variabel Random tensor dan prime tensor\n")
print("------------------    ++    -------------    ++    ------------------\n")
print("                      ", perkalian, "\n\n------------------    ++    -------------    ++    ------------------\n")


------------------    ++    -------------    ++    ------------------

      Hasil Perkalian Variabel Random tensor dan prime tensor

------------------    ++    -------------    ++    ------------------

                       tf.Tensor(
[[  -0.7488936    1.8558043   -3.096067     6.3871546    7.6450667]
 [  -2.3336303   -6.3854656   -2.565165    15.356451    12.302258 ]
 [  -9.717599   -10.079487    48.60244     14.757771    68.177155 ]
 [ -15.79227    -83.616714    37.023254   -94.20834    -62.341003 ]
 [ -29.474854    29.301016   -89.02344    -66.54574   -115.369446 ]], shape=(5, 5), dtype=float32) 

------------------    ++    -------------    ++    ------------------



## Pembagian

In [72]:
pembagian = tf.divide(random_tensor, prime_tensor)

print("\n------------------    ++    -------------    ++    ------------------")
print("\n      Hasil Pembagian Variabel Random tensor dan prime tensor\n")
print("------------------    ++    -------------    ++    ------------------\n")
print("                      ", pembagian, "\n\n------------------    ++    -------------    ++    ------------------\n")


------------------    ++    -------------    ++    ------------------

      Hasil Pembagian Variabel Random tensor dan prime tensor

------------------    ++    -------------    ++    ------------------

                       tf.Tensor(
[[-0.1872234   0.20620048 -0.12384268  0.1303501   0.06318237]
 [-0.01380846 -0.02209504 -0.00710572  0.02902921  0.01462813]
 [-0.01011197 -0.00736266  0.02891281  0.00798149  0.03086336]
 [-0.00562203 -0.02402089  0.00994981 -0.02098649 -0.01236679]
 [-0.00553103  0.00469492 -0.01292255 -0.00840118 -0.01226161]], shape=(5, 5), dtype=float32) 

------------------    ++    -------------    ++    ------------------



## Logaritma

In [73]:
logaritma = tf.math.log(random_tensor, prime_tensor)

print("\n------------------    ++    -------------    ++    ------------------")
print("\n      Hasil Logaritma Variabel Random tensor dan prime tensor\n")
print("------------------    ++    -------------    ++    ------------------\n")
print("                      ", logaritma, "\n\n------------------    ++    -------------    ++    ------------------\n")


------------------    ++    -------------    ++    ------------------

      Hasil Logaritma Variabel Random tensor dan prime tensor

------------------    ++    -------------    ++    ------------------

                       tf.Tensor(
[[        nan -0.4802941          nan -0.09162126 -0.36383468]
 [        nan         nan         nan -0.40395853 -0.857513  ]
 [        nan         nan  0.17010169 -1.0694304   0.37196195]
 [        nan         nan -0.49932766         nan         nan]
 [        nan -0.9918257          nan         nan         nan]], shape=(5, 5), dtype=float32) 

------------------    ++    -------------    ++    ------------------



## Pangkat

In [74]:
pangkat = tf.pow(random_tensor, prime_tensor)

print("\n------------------    ++    -------------    ++    ------------------")
print("\n      Hasil Pangkat Variabel Random tensor dan prime tensor\n")
print("------------------    ++    -------------    ++    ------------------\n")
print("                      ", pangkat, "\n\n------------------    ++    -------------    ++    ------------------\n")


------------------    ++    -------------    ++    ------------------

      Hasil Pangkat Variabel Random tensor dan prime tensor

------------------    ++    -------------    ++    ------------------

                       tf.Tensor(
[[ 1.40210420e-01  2.36718819e-01 -9.10336077e-02  5.26581705e-01
   1.82757247e-02]
 [-2.00980191e-10 -5.89714872e-08 -2.99828488e-17  9.22464751e-05
   1.58495942e-11]
 [-2.41054618e-16 -1.26986502e-21  1.06866943e+03  1.06843616e-20
   3.91225680e+07]
 [-1.35188438e-28 -8.61039680e+08  5.91330506e-14 -8.25991680e+09
  -9.76327356e-05]
 [-1.76767207e-29  9.35817252e-35 -3.35258301e+02 -5.78084585e-12
  -2.02279100e+07]], shape=(5, 5), dtype=float32) 

------------------    ++    -------------    ++    ------------------



### --------------------------------------------------------------------------------------------------------------------
### Tampilkan nilai maksimal dan minimal dari variable random_tensor
### --------------------------------------------------------------------------------------------------------------------

In [78]:
nilaiMax = tf.argmax(random_tensor, axis = 0)

print("\n----------    ++    -------------    ++    ----------")
print("\n         Nilai Maximal Variable Prime Tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print(nilaiMax, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

         Nilai Maximal Variable Prime Tensor

----------    ++    -------------    ++    ----------

tf.Tensor([1 0 2 0 2], shape=(5,), dtype=int64) 

----------    ++    -------------    ++    ----------



In [79]:
nilaiMin = tf.argmin(random_tensor, axis = 0)

print("\n----------    ++    -------------    ++    ----------")
print("\n         Nilai Minimal Variable Prime Tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print(nilaiMin, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

         Nilai Minimal Variable Prime Tensor

----------    ++    -------------    ++    ----------

tf.Tensor([4 3 4 3 4], shape=(5,), dtype=int64) 

----------    ++    -------------    ++    ----------



### --------------------------------------------------------------------------------------------------------------------
### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)
### --------------------------------------------------------------------------------------------------------------------

In [83]:
nilaiConcat = tf.concat([random_tensor, prime_tensor], axis = 0)

print("\n------------------    ++    -------------    ++    ------------------")
print("\n      Hasil Penggabungan Variabel Random tensor dan prime tensor\n")
print("------------------    ++    -------------    ++    ------------------\n")
print(nilaiConcat, "\n\n------------------    ++    -------------    ++    ------------------\n")


------------------    ++    -------------    ++    ------------------

      Hasil Penggabungan Variabel Random tensor dan prime tensor

------------------    ++    -------------    ++    ------------------

tf.Tensor(
[[-0.3744468   0.61860144 -0.6192134   0.9124507   0.6950061 ]
 [-0.17951003 -0.37561563 -0.1350087   0.6676718   0.4242158 ]
 [-0.31347093 -0.27241856  1.1854254   0.34320396  1.4505777 ]
 [-0.29796734 -1.4172324   0.6069386  -1.4060947  -0.8780423 ]
 [-0.4037651   0.37089893 -1.0725715  -0.7477049  -1.1893758 ]
 [ 2.          3.          5.          7.         11.        ]
 [13.         17.         19.         23.         29.        ]
 [31.         37.         41.         43.         47.        ]
 [53.         59.         61.         67.         71.        ]
 [73.         79.         83.         89.         97.        ]], shape=(10, 5), dtype=float32) 

------------------    ++    -------------    ++    ------------------



### --------------------------------------------------------------------------------------------------------------------
### Tampilkan hasil sorting dari kedua variable di atas. (descending)
### --------------------------------------------------------------------------------------------------------------------

In [85]:
sortRandom = tf.sort(random_tensor, direction = "DESCENDING")

print("\n----------    ++    -------------    ++    ----------")
print("\n      Sorting Descending Variable Prime Tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print(sortRandom, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

      Sorting Descending Variable Prime Tensor

----------    ++    -------------    ++    ----------

tf.Tensor(
[[ 0.9124507   0.6950061   0.61860144 -0.3744468  -0.6192134 ]
 [ 0.6676718   0.4242158  -0.1350087  -0.17951003 -0.37561563]
 [ 1.4505777   1.1854254   0.34320396 -0.27241856 -0.31347093]
 [ 0.6069386  -0.29796734 -0.8780423  -1.4060947  -1.4172324 ]
 [ 0.37089893 -0.4037651  -0.7477049  -1.0725715  -1.1893758 ]], shape=(5, 5), dtype=float32) 

----------    ++    -------------    ++    ----------



In [86]:
sortPrime = tf.sort(prime_tensor, direction = "DESCENDING")

print("\n----------    ++    -------------    ++    ----------")
print("\n      Sorting Descending Variable Prime Tensor\n")
print("----------    ++    -------------    ++    ----------\n")
print(sortPrime, "\n\n----------    ++    -------------    ++    ----------\n")


----------    ++    -------------    ++    ----------

      Sorting Descending Variable Prime Tensor

----------    ++    -------------    ++    ----------

tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32) 

----------    ++    -------------    ++    ----------

